logging:
  level:
    .: error
    org.springframework: ERROR
    com.ibm: ERROR

spring:
  profiles:
    default: "prod"
  main:
    banner-mode: "off"

server:
  email: default@ibm.com

---

spring:
  config :
    activate :
      on-profile : "dev"
server:
  email: dev@ibm.com
  cluster:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3

---

spring:
  config :
    activate :
      on-profile : "prod"
server:
  email: prod@ibm.com
  cluster:
    - ip: 192.168.0.1
      path: /app1
    - ip: 192.168.0.2
      path: /app2
    - ip: 192.168.0.3
      path: /app3
